spring:
  data:
    mongodb:
      host: mongo
      username: root
      password: secret
      database: logicforge
      authentication-database: logicforge
      uuid-representation: standard
  main:
    banner-mode: off
